name: Deploy Streamlit App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Streamlit
      env:
        TIDB_URL: ${{ secrets.TIDB_URL }}
        EMBEDDING_API_URL: ${{ secrets.EMBEDDING_API_URL }}
        EMBEDDING_MODEL: ${{ secrets.EMBEDDING_MODEL }}
      run: |
        streamlit run app.py --server.port 8501 --server.address 0.0.0.0 --server.headless true
        
  # สำหรับ deploy ไปยัง Streamlit Cloud หรือ external service
  streamlit-cloud:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to Streamlit Cloud
      run: |
        echo "🚀 Ready for Streamlit Cloud deployment"
        echo "📝 Instructions:"
        echo "1. Go to https://share.streamlit.io"
        echo "2. Connect your GitHub repository"
        echo "3. Set main file as 'app.py'"
        echo "4. Add secrets in Streamlit Cloud dashboard"
