name: Run Embedding

on:
  workflow_dispatch:

jobs:
  embed:
    runs-on: ubuntu-latest
    environment: TIDB_URL  # <<< ตรงนี้! ต้องชี้ไปที่ชื่อ Environment ของคุณให้ตรง

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          TIDB_URL: ${{ secrets.TIDB_URL }}
          EMBEDDING_API_URL: ${{ secrets.EMBEDDING_API_URL }}
          EMBEDDING_MODEL: ${{ secrets.EMBEDDING_MODEL }}
        run: python main.py
