[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#3b82f6"
backgroundColor = "#0a0e27"
secondaryBackgroundColor = "#1e293b"
textColor = "#e1e5f1"
